### ISSUE TITLE
Site: static site generator revamp

### ISSUE THREAD

**Issue by fahad19** [frintjs/frint#232]
At the moment, the site at https://frint.js.org is generated with Metalsmith, and not really in a great shape for maintenance.

Would be worth giving some other tools a try. A few that I can think of:

* Jekyll: https://jekyllrb.com/
* GatsbyJS: https://www.gatsbyjs.org/

More feedback welcome.

**Comment by etiennetremel** [comment]
Nice tool, but GoLang based:
- Hugo: http://gohugo.io "The world’s fastest framework for building websites" (catchy marketing speech)

**Comment by mAAdhaTTah** [comment]
Docusaurus looks promising: http://docusaurus.io/ - I'm going to be using it for a project myself.

**Comment by fahad19** [comment]
Done by @maryam-saeidi in https://github.com/frintjs/frint.js.org/pull/11
