### ISSUE TITLE
Usage questions: frint-router, regions and updating regions

### ISSUE THREAD

**Issue by fahadsuhaib** [frintjs/frint#369]
I couldn't understand the following things based on the guides, so raising an issue ticket here,

_Question 1:_
The guides and examples are defining two different approaches with regions n routes, but never used both. What is the ideal way to use them both? I see there is an "app" props,

https://github.com/frintjs/frint/blob/master/examples/router/root/components/Root.js

<Route path="/services" app={ServicesApp} />

_Question 2:_
How to replace a region with another component dynamically (multi:false)? Consider I have a "content" region and I would be loading with <ComponentA> and after some UI actions load <ComponentB>.

**Comment by fahad19** [comment]
> Question 1:
> The guides and examples are defining two different approaches with regions n routes, but never used both. What is the ideal way to use them both? I see there is an "app" props,

Routes react to the URLs in your browser. And based on that, it renders Components or Apps.

Regions are defined with specific names, like `sidebar` or `footer` for example. They have nothing to do with URLs/Routes. Whenever a Region is active, and there is a registered Child App targeting that Region, that particular App will render there.

**Comment by fahad19** [comment]
> Question 2:
> How to replace a region with another component dynamically (multi:false)? Consider I have a "content" region and I would be loading with and after some UI actions load .

In the end, Region is just a component. You can add conditions in your JSX like this:

```js
function MyComponent(props) {
  return (
    <div>
      {props.showSidebar && <Region name="sidebar" />}

      {!props.showSidebar && <SomeOtherComponent />}
    </div>
  );
}
```

**Comment by fahadsuhaib** [comment]
Thanks on Q1, on Q2 I was not very clear :), What I mean is there is already a <ComponentA/> that registers with the region='sidebar', Can I load another <ComponentB/> to the same region='sidebar'?

**Comment by fahadsuhaib** [comment]
Thanks! this works well.
