### ISSUE TITLE
Is FrintJS compatible with Apollo 2.0?

### ISSUE THREAD

**Issue by loganpowell** [frintjs/frint#407]
Very excited to see this library! Question about modularity of Frint: 

Now that [Apollo has adopted observables](https://www.apollographql.com/docs/link/overview.html), how well might `frint` and `apollo` play together?

**Comment by fahad19** [comment]
Hi @loganpowell! Thanks for your interest!

Few things to understand about FrintJS packages:

## `frint`

This package is for creating Apps (and Child Apps), and for defining the dependencies as Providers. It has nothing to do with rendering, or anything browser specific.

```js
import { createApp } from 'frint';

const MyApp = createApp({
  name: 'MyApp',
  providers: [
    { name: 'foo', useValue: 'bar' }
  ],
});

const app = new MyApp();
const foo = app.get('foo'); // `bar`
```

## `frint-react`

This package is for integrating React with FrintJS apps.

### Rendering

It allows you to render your FrintJS apps to DOM:

```js
import React from 'react';
import { createApp } from 'frint';
import { render } from 'frint-react';

function MyComponent() {
  return <p>Hello World</p>;
}  

const MyApp = createApp({
  name: 'MyApp',
  providers: [
    { name: 'component', useValue: MyComponent }
  ],
});

const app = new MyApp();
render(app, document.getElementById('root'));
```

### Streaming props

It ships a higher-order component called `observe` that allows access to your App instance, where you can get access to your Providers.

Now it is totally up to you to either generate props for your base component synchronously, or stream it using Observable:

```js
// MyComponent.js
import React from 'react';
import { observe } from 'frint-react';

function MyComponent(props) {
  return <p></p>;
}

export default observe(function (app) {
  const props = {};

  // synchronous
  return props;

  // stream
  return new Observable.of(props);
})(MyComponent);
```

## Apollo integration

I haven't worked with Apollo myself, but I see it integrating with FrintJS+React like this.

All the stateful dependencies of your FrintJS App are expected to be set as providers. So your Apollo client could be a provider here:

```js
import ApolloClient from 'apollo-client-preset';
import { createApp } from 'frint';

const MyApp = createApp({
  name: 'MyApp',
  providers: [
    {
      name: 'apollo',
      useFactory() {
        return new ApolloClient();
      },
    },
  ]
});
```

Now you can access the client from anywhere in your React components tree using the `observe` higher-order component:

```js
import React from 'react';
import { observe } from 'frint-react';

function MyComponent() {
  return <p></p>;
}

export default observe(function (app) {
  const client = app.get('apollo');

  return {}; // or Observable of props
})(MyComponent);
```

What if you wanted to use `react-apollo` and its `graphql` component enhancer?

```js
import React from 'react';
import ApolloClient from 'apollo-client-preset';
import { ApolloProvider } from 'react-apollo';
import { createApp } from 'frint';

function Root() {
  return <p></p>;
}

const MyApp = createApp({
  name: 'MyApp',
  providers: [
    // we define our client first
    {
      name: 'apollo',
      useFactory() {
        return new ApolloClient();
      },
    },

    // we define our component, and inject `apollo` as a dependency to it
    {
      name: 'component',
      deps: ['apollo'],
      useFactory({ apollo }) {
        return (
          <ApolloProvider client={apollo}>
            <Root />
          </ApolloProvider>
        );
      },
    },
  ]
});
```

That way, your client is set as a provider, and also lets you use the `graphql` HoC from `react-apollo` anywhere from your components tree:

```js
// components/Todo.js
import { graphql } from 'react-apollo';
import gql from 'graphql-tag';

function TodoApp({ data: { todos, refetch } }) {
  return (
    <div>
      <button onClick={() => refetch()}>Refresh</button>
      <ul>{todos && todos.map(todo => <li key={todo.id}>{todo.text}</li>)}</ul>
    </div>
  );
}

export default graphql(gql`
  query TodoAppQuery {
    todos {
      id
      text
    }
  }
`)(TodoApp);
```

Hope that helps!

**Comment by loganpowell** [comment]
Dude, that was amazing. Thank you!!!

**Comment by fahad19** [comment]
Closing this issue assuming it answered everything you needed to know for now.

For further reading:

* Hello World guide: https://frint.js.org/guides/hello-world/
* Providers: https://frint.js.org/docs/packages/frint/#understanding-providers
* The `observe` higher-order component: https://frint.js.org/guides/higher-order-components/
* `frint-props`: https://github.com/frintjs/frint-props

**Comment by loganpowell** [comment]
Just a couple of questions/notes for posterity:

1) it seems that `apollo-link` is [using zen observable](https://github.com/apollographql/apollo-link/blob/master/package.json#L89). How might this affect its use with `observe` from `frint`?
2) There's a popular library ([recompose](https://github.com/acdlite/recompose/blob/master/docs/API.md#observable-utilities)) that contains an API for working with observables. Might you be interested in using it? Might give you a nice 'hook' into the community ;)

**Comment by fahad19** [comment]
> it seems that apollo-link is using zen observable. How might this affect its use with observe from frint?

RxJS v5+ follows the TC39 spec (just like `zen-observable`) as defined here: https://github.com/tc39/proposal-observable

As long as you return a valid Observable of props, it will work just fine with the `observe` higher-order component

---

> There's a popular library (recompose) that contains an API for working with observables. Might you be interested in using it? Might give you a nice 'hook' into the community ;)

Recompose is really great, and has been a source of inspiration for `frint-props` here: https://github.com/frintjs/frint-props

FrintJS does not want to tie itself to any rendering library too closely, and two of its key goals include:

* Being environment agnostic (run on server, browser, CLI, anywhere)
* Agnostic of any rendering library (React or Vue)

If we want to integrate with any rendering library, we create integration packages like we have for React and Vue.js via `frint-react` and `frint-vue` respectively.

If you want to use Recompose+React+FrintJS together in your application, you always can.

**Comment by loganpowell** [comment]
> FrintJS does not want to tie itself to any rendering library too closely, and two of its key goals include:

Ah, yes! I forgot that point. `frint` is render-agnostic. Thank you for your patience!
