### ISSUE TITLE
Frint CLI Issues

### ISSUE THREAD

**Issue by loganpowell** [frintjs/frint#409]
Hi!

Just getting started with Frint and I figured I'd just `-g frint-cli` to get started. However, I've just a couple questions about what I'm getting from `frint new`:

In the `package.json`:
```js
    "frint": "^3.3.1",
    "frint-react": "^3.3.1",
    "frint-store": "^3.3.1",
    "lodash": "^4.17.4",
    "prop-types": "^15.5.10",
    "react": "^16.0.0",
    "react-dom": "^16.0.0",
    "rxjs": "^5.5.0"
```
Shouldn't I be seeing `frint... 5.x`?

Also, I didn't load any examples and just wanted a bare-bones starter, but it seems there might be a Redux example in the bare `frint new` project, unless I missed the fact that `frint` is modelled after Redux's actions, reducers, constants model. The name of the project is `"frint-example-counter"`

Forgive me if I've missed the fact that I'll have to use the Redux pattern to use Frint.

**Comment by fahad19** [comment]
> Shouldn't I be seeing frint... 5.x?

Whenever you use `$ frint new`, it scaffolds an example application from this directory of our monorepo: https://github.com/frintjs/frint/tree/master/examples

We have an issue here for upgrading all our examples to latest version of FrintJS here: https://github.com/frintjs/frint/issues/352

---

> frint is modelled after Redux's actions, reducers, constants model

It's not. 

It is up to the application developer to decide what suits best in your application. If you want Mobx, use Mobx. If Redux or Apollo, that is fine too.

FrintJS only expects your application-wide stateful dependencies to be defined as Providers, and gives access to them via the `observe` higher-order component.

Either you put Redux store, or RxJS Subject there, or a Model from `frint-data`, is of no concern to FrintJS :)

**Comment by loganpowell** [comment]
Thank you! Closing.
