### ISSUE TITLE
Project still alive?

### ISSUE THREAD

**Issue by mikkelking** [frintjs/frint#441]
Is this project still alive? It's almost a year since the last issue raised.

Does it have a future?

**Comment by alexmiranda** [comment]
It has lost traction. I know @fahad19's been busy with https://github.com/fahad19/proppy
None of the open issues are ground-breaking, so I wouldn't expect a major version coming up anytime soon. There are however lots of nice-to-have items left there to anyone to pick up.
Perhaps Fahad has an idea for the future and ownership of this project?

**Comment by fahad19** [comment]
Hi @mikkelking! Thanks for the question.

From features perspective, we are 100% there where we wanted to be. No new features are planned or being worked upon. No major known issues either. 

We have some proposals in the issues, which can add to the ecosystem. But they can be built by anyone in the form of additional packages. The core still remains small and simple.

Hope that answers your question.
